apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: jenkins
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    build:
      artifacts:
      - image: johnnyhuy/jenkins
        context: .
        docker:
          dockerfile: Dockerfile
    deploy:
      kustomize:
        paths:
          - overlays/local
    portForward:
      - resourceType: service
        resourceName: jenkins
        namespace: default
        port: 8080