minikube:
  enabled: false

kube-prometheus-stack:
  fullnameOverride: prometheus
  alertmanager:
    enabled: false
    alertmanagerSpec:
      fullnameOverride: alertmanager

  grafana:
    enabled: true
    fullnameOverride: grafana
    serviceMonitor:
      enabled: false
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        jenkins:
          gnetId: 9964
          revision: 1
          datasource: Prometheus

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: true

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  kubeStateMetrics:
    enabled: true

  kube-state-metrics:
    fullnameOverride: kube-state-metrics

  nodeExporter:
    enabled: true

  prometheus-node-exporter:
    fullnameOverride: node-exporter

  prometheusOperator:
    serviceMonitor:
      selfMonitor: false

  prometheus:
    serviceMonitor:
      selfMonitor: false
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
  