minikube:
  enabled: true

  
jenkins:

  config:
    jenkins:
      disableRememberMe: false
      mode: NORMAL
      numExecutors: 0
      labelString: ""
      projectNamingStrategy: "standard"
      markupFormatter:
        plainText
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true

    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: false
    
    jobs:
      - script: >
          folder('testjobs')
      - script: >
          pipelineJob('testjobs/default-agent') {
            definition {
              cps {
                script("""\
                  pipeline {
                    agent any
                    stages {
                      stage ('test') {
                        steps {
                          echo "hello"
                        }
                      }
                    }
                  }""".stripIndent())
              }
            }
          }

  agents:
    default:
      label: "default"
      containers:
      - name: "jnlp"
        image: "jenkins/inbound-agent:4.11.2-4"
    gradle:
      label: "gradle"
      containers:
      - name: "jnlp"
        image: "johnnyhuy/jenkins-gradle:latest"
    node:
      label: "node"
      containers:
      - name: "jnlp"
        image: "johnnyhuy/jenkins-node:latest"