minikube:
  enabled: true

jenkins:
  controller:
    sidecars:
      configAutoReload:
        enabled: true
    containerEnv:
      - name: PUBLIC_JENKINS_URL
        value: "http://localhost:8080"
      - name: PRIVATE_JENKINS_URL
        value: "http://jenkins.jenkins.svc.cluster.local:8080"
  cascConfig:
    jenkins:
      disableRememberMe: false
      mode: NORMAL
      numExecutors: 0
      labelString: ""
      projectNamingStrategy: "standard"
      markupFormatter:
        plainText
      clouds:
      - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          jenkinsUrl: $PRIVATE_JENKINS_URL
          jenkinsTunnel: "jenkins-agent:50000"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: jenkins
          serverUrl: "https://kubernetes.default"
          podLabels:
          - key: "jenkins/jenkins-jenkins-agent"
            value: "true"
          templates:
            - name: "default"
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://${PRIVATE_JENKINS_URL}:8080/"
                image: "jenkins/inbound-agent:4.11.2-4"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              idleMinutes: 0
              instanceCap: 2147483647
              label: "default"
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              serviceAccount: default
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
            - name: "gradle"
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://${PRIVATE_JENKINS_URL}:8080/"
                image: "johnnyhuy/jenkins-gradle:latest"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              idleMinutes: 0
              instanceCap: 2147483647
              label: "gradle"
              nodeUsageMode: "EXCLUSIVE"
              podRetention: Never
              showRawYaml: true
              serviceAccount: default
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
            - name: "node"
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://${PRIVATE_JENKINS_URL}:8080/"
                image: "johnnyhuy/jenkins-node:latest"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              idleMinutes: 0
              instanceCap: 2147483647
              label: "node"
              nodeUsageMode: "EXCLUSIVE"
              podRetention: Never
              showRawYaml: true
              serviceAccount: default
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: false
    unclassified:
      location:
        adminAddress: 
        url: $PUBLIC_JENKINS_URL