apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  template:
    spec:
      containers:
        - name: jenkins
          volumeMounts:
            - mountPath: /var/jenkins_home/casc_configs
              name: jenkins-config
      volumes:
        - name: jenkins-config
          configMap:
            name: jenkins-config