kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - openldap.yaml

configMapGenerator:
  - name: jenkins-config
    files:
      - jenkins-config.yaml

patches:
  - path: jenkins.yaml
