{{ if .Values.minikube.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minikube-java-app
spec:
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: java-app
---
{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: java-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: {{ .Values.java.replicas }}
  selector:
    matchLabels:
      kubernetes.io/name: java-app
  template:
    metadata:
      labels:
        kubernetes.io/name: java-app
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.java.image.repository }}:{{ .Values.java.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
