{{ if .Values.minikube.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minikube-node-app
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: node-app
---
{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: node-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      kubernetes.io/name: node-app
  template:
    metadata:
      labels:
        kubernetes.io/name: node-app
    spec:
      containers:
        - name: node-app
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
