apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      serviceAccountName: kubedoom
      containers:
        - image: ghcr.io/storax/kubedoom:latest
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: {{ .Release.Namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubedoom
    namespace: {{ .Release.Namespace }}