apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-config
  namespace: {{ .Release.Namespace }}
  labels:
    jenkins-jenkins-config: "true"
data:
  config.yaml: |-
    {{- toYaml .Values.jenkins.config | nindent 4 }}
  kubernetes.yaml: |-
    {{- include "jenkins.casc.kubernetes" . | nindent 4 }}
