{{ if .Values.minikube.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minikube-jenkins
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.jenkins.controller.servicePort }}
      name: http
      targetPort: {{ .Values.jenkins.controller.targetPort }}
  selector:
    "app.kubernetes.io/component": "{{ .Values.jenkins.controller.componentName }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  type: LoadBalancer
{{ end }}
